# Generated by Django 4.0.2 on 2022-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_report_report_time_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='send_report',
            field=models.BooleanField(default=True),
        ),
    ]
